# Generated by Django 5.1.13 on 2025-11-18 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0049_alter_layermetadata_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='layersubmission',
            name='file_size',
            field=models.BigIntegerField(blank=True, help_text='File size in bytes.', null=True),
        ),
    ]
