# Generated by Django 5.1.13 on 2025-11-06 06:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0056_alter_geoservergroupuser_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='geoserverpublishchannel',
            name='gpkg_memory_map_size',
            field=models.IntegerField(blank=True, help_text='Optional. The memory map size in Megabytes (MB) for this GeoPackage data store. Leave blank to use the GeoServer default.', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='GeoPackage Memory Map Size (MB)'),
        ),
    ]
