# Generated by Django 5.1.13 on 2025-11-18 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0057_geoserverpublishchannel_gpkg_memory_map_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geoserverpublishchannel',
            name='expire_client_cache_after_n_seconds',
            field=models.IntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='geoserverpublishchannel',
            name='expire_server_cache_after_n_seconds',
            field=models.IntegerField(default=300),
        ),
    ]
