# Generated by Django 5.1.13 on 2025-12-23 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0058_alter_geoserverpublishchannel_expire_client_cache_after_n_seconds_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoserverClusterPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_url', models.CharField(max_length=500)),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('enabled', models.BooleanField(default=True)),
                ('geoserver_pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cluster_nodes', to='publisher.geoserverpool')),
            ],
            options={
                'verbose_name': 'GeoServer Cluster Pool Node',
                'verbose_name_plural': 'GeoServer Cluster Pool Nodes',
            },
        ),
    ]
