# Generated by Django 5.2.11 on 2026-02-27 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0059_geoserverclusterpool'),
    ]

    operations = [
        migrations.AddField(
            model_name='geoserverqueue',
            name='queue_type',
            field=models.IntegerField(choices=[(0, 'Publish'), (1, 'Purge Cache')], default=0),
        ),
    ]
