# Generated by Django 5.2.12 on 2026-03-17 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0060_add_queue_type_to_geoserver_queue'),
    ]

    operations = [
        migrations.AddField(
            model_name='geoserverqueue',
            name='converted_file_path',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='geoserverqueue',
            name='status',
            field=models.IntegerField(choices=[(0, 'Ready'), (1, 'Processing'), (2, 'Published'), (3, 'Failed'), (4, 'Converted'), (5, 'Upload In Progress'), (6, 'Upload Failed'), (7, 'Ready To Publish'), (8, 'Publish Failed')], default=0),
        ),
    ]
