# Generated by Django 5.2.12 on 2026-03-31 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0061_add_new_geoserver_queue_statuses_and_converted_file_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoServerLayerGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the layer group as it will appear in GeoServer.', max_length=255)),
                ('title', models.CharField(blank=True, help_text='Human-readable title displayed in WMS capabilities.', max_length=255, null=True)),
                ('abstract', models.TextField(blank=True, help_text='Description of the layer group.', null=True)),
                ('published_name', models.CharField(blank=True, help_text="The name under which this group was last published to GeoServer. Null means the group has never been published. Differs from 'name' when the user has renamed the group since the last publish; in that case the old name is deleted from GeoServer and the new name is created.", max_length=255, null=True)),
                ('active', models.BooleanField(default=True, help_text='Inactive groups are ignored by publish operations.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('geoserver_pool', models.ForeignKey(help_text='All member layers must target this GeoServer pool.', on_delete=django.db.models.deletion.CASCADE, related_name='layer_groups', to='publisher.geoserverpool')),
                ('workspace', models.ForeignKey(help_text='All member layers must belong to this workspace.', on_delete=django.db.models.deletion.CASCADE, related_name='layer_groups', to='publisher.workspace')),
            ],
            options={
                'verbose_name': 'GeoServer Layer Group',
                'verbose_name_plural': 'GeoServer Layer Groups',
                'unique_together': {('workspace', 'name')},
            },
        ),
        migrations.CreateModel(
            name='GeoServerLayerGroupEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Rendering order within the group (0 = bottom of stack).')),
                ('layer_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='publisher.geoserverlayergroup')),
                ('publish_channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layer_group_entries', to='publisher.geoserverpublishchannel')),
            ],
            options={
                'verbose_name': 'GeoServer Layer Group Entry',
                'verbose_name_plural': 'GeoServer Layer Group Entries',
                'ordering': ['order'],
                'unique_together': {('layer_group', 'publish_channel')},
            },
        ),
    ]
