# Generated by Django 5.2.12 on 2026-04-02 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0062_add_geoserver_layer_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='geoserverlayergroup',
            name='needs_republish',
            field=models.BooleanField(default=False, help_text='Set to True automatically when member layers are added or removed after the last publish. Cleared on successful publish.'),
        ),
    ]
