# Generated by Django 5.2.12 on 2026-04-02 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0063_add_needs_republish_to_layer_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geoserverlayergroup',
            name='active',
        ),
    ]
